package com.limitless.services.engage.upi.dao;

// Generated Oct 24, 2016 8:29:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UpiOrder generated by hbm2java
 */
@Entity
@Table(name = "upi_order", catalog = "llcdb")
public class UpiOrder implements java.io.Serializable {
	
	@Id @GeneratedValue
	@Column(name="ORDER_ID")
	private Integer orderId;
	@Column(name="CUSTOMER_ID")
	private int customerId;
	@Column(name="ORDER_AMOUNT")
	private float orderAmount;
	@Column(name="ORDER_STATUS")
	private String orderStatus;
	@Column(name="ORDER_CREATED_TIME")
	private Date orderCreatedTime;
	@Column(name="ORDER_UPDATED_TIME")
	private Date orderUpdatedTime;

	public UpiOrder() {
	}

	public UpiOrder(int customerId, float orderAmount) {
		this.customerId = customerId;
		this.orderAmount = orderAmount;
	}

	public UpiOrder(int customerId, float orderAmount, String orderStatus,
			Date orderCreatedTime, Date orderUpdatedTime) {
		this.customerId = customerId;
		this.orderAmount = orderAmount;
		this.orderStatus = orderStatus;
		this.orderCreatedTime = orderCreatedTime;
		this.orderUpdatedTime = orderUpdatedTime;
	}

	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	public float getOrderAmount() {
		return this.orderAmount;
	}

	public void setOrderAmount(float orderAmount) {
		this.orderAmount = orderAmount;
	}

	public String getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}

	public Date getOrderCreatedTime() {
		return this.orderCreatedTime;
	}

	public void setOrderCreatedTime(Date orderCreatedTime) {
		this.orderCreatedTime = orderCreatedTime;
	}

	public Date getOrderUpdatedTime() {
		return this.orderUpdatedTime;
	}

	public void setOrderUpdatedTime(Date orderUpdatedTime) {
		this.orderUpdatedTime = orderUpdatedTime;
	}

}
