package com.limitless.services.engage.upi.dao;

// Generated Oct 24, 2016 8:29:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * UpiOrder generated by hbm2java
 */
@Entity
@Table(name = "upi_icici")
public class UpiOrder implements java.io.Serializable {
	
	@Id @GeneratedValue
	@Column(name="ORDER_ID")
	private Integer orderId;
	
	@Column(name="CUSTOMER_ID")
	private int customerId;
	
	@Column(name="SELLER_ID")
	private int sellerId;
	
	@Column(name="ORDER_AMOUNT")
	private float orderAmount;
	
	@Column(name="TXN_NOTES")
	private String txnNotes;
	
	@Column(name="ICICI_TXN_NO")
	private String iciciTxnNo;
	
	@Column(name="ICICI_TXN_TIME")
	private String iciciTxnTime;
	
	@Column(name="ORDER_STATUS")
	private String orderStatus;
	
	@Column(name="ORDER_PAYMENT_TYPE")
	private String orderPaymentType;
	
	@Column(name="ORDER_ERROR_CODE")
	private String orderErrorCode;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="ORDER_CREATED_TIME", insertable = false, updatable = false)
	private Date orderCreatedTime;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="ORDER_UPDATED_TIME")
	@Version
	private Date orderUpdatedTime;

	public UpiOrder() {
	}

	public UpiOrder(int customerId, int sellerId, float orderAmount) {
		this.customerId = customerId;
		this.sellerId = sellerId;
		this.orderAmount = orderAmount;
	}

	public UpiOrder(int customerId, int sellerId, float orderAmount, String txnNotes, String iciciTxnNo, String iciciTxnTime, String orderStatus, String orderPaymentType,
			Date orderCreatedTime, Date orderUpdatedTime) {
		this.customerId = customerId;
		this.sellerId = sellerId;
		this.orderAmount = orderAmount;
		this.txnNotes = txnNotes;
		this.iciciTxnNo = iciciTxnNo;
		this.iciciTxnTime = iciciTxnTime;
		this.orderStatus = orderStatus;
		this.orderPaymentType = orderPaymentType;
		this.orderCreatedTime = orderCreatedTime;
		this.orderUpdatedTime = orderUpdatedTime;
	}

	public int getSellerId() {
		return sellerId;
	}

	public void setSellerId(int sellerId) {
		this.sellerId = sellerId;
	}

	public String getIciciTxnNo() {
		return iciciTxnNo;
	}

	public void setIciciTxnNo(String icicTxnNo) {
		this.iciciTxnNo = icicTxnNo;
	}

	public String getIciciTxnTime() {
		return iciciTxnTime;
	}

	public void setIciciTxnTime(String iciciTxnTime) {
		this.iciciTxnTime = iciciTxnTime;
	}

	public String getOrderPaymentType() {
		return orderPaymentType;
	}

	public void setOrderPaymentType(String orderPaymentType) {
		this.orderPaymentType = orderPaymentType;
	}

	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	public float getOrderAmount() {
		return this.orderAmount;
	}

	public void setOrderAmount(float orderAmount) {
		this.orderAmount = orderAmount;
	}

	public String getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}

	public Date getOrderCreatedTime() {
		return this.orderCreatedTime;
	}

	public void setOrderCreatedTime(Date orderCreatedTime) {
		this.orderCreatedTime = orderCreatedTime;
	}

	public Date getOrderUpdatedTime() {
		return this.orderUpdatedTime;
	}

	public void setOrderUpdatedTime(Date orderUpdatedTime) {
		this.orderUpdatedTime = orderUpdatedTime;
	}

	public String getOrderErrorCode() {
		return orderErrorCode;
	}

	public void setOrderErrorCode(String orderErrorCode) {
		this.orderErrorCode = orderErrorCode;
	}

	public String getTxnNotes() {
		return txnNotes;
	}

	public void setTxnNotes(String txnNotes) {
		this.txnNotes = txnNotes;
	}
	
	
}
