package com.limitless.services.engage.dao;

// Generated Oct 14, 2016 12:16:26 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityResult;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;
import javax.persistence.SqlResultSetMapping;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.Version;

import org.hibernate.annotations.Formula;

import com.limitless.services.socialentity.dao.*;

/**
 * EngageSeller generated by hbm2java
 */
@Entity
@Table(name = "engage_seller", catalog = "llcdb")
@SqlResultSetMapping(name = "engage_seller", entities = @EntityResult(entityClass = EngageSeller.class))
public class EngageSeller implements java.io.Serializable {

	@Id
	@GeneratedValue
	@Column(name = "SELLER_ID")

	private int sellerId;
	@Column(name = "SELLER_NAME")
	private String sellerName;
	@Column(name = "SELLER_EMAIL99")
	private String sellerEmail99;
	@Column(name = "SELLER_PASSWD99")
	private String sellerPasswd99;
	@Column(name = "SELLER_COUNTRY_CODE")
	private String sellerCountryCode;
	@Column(name = "SELLER_MOBILE_NUMBER")
	private String sellerMobileNumber;
	@Column(name = "SELLER_COUNTRY")
	private String sellerCountry;
	@Column(name = "SELLER_CITY")
	private String sellerCity;
	@Column(name = "SELLER_ADDRESS")
	private String sellerAddress;
	@Column(name = "SELLER_DEVICE_ID")
	private String sellerDeviceId;
	@Column(name = "SELLER_LOCATION_LATITUDE")
	private double sellerLocationLatitude;
	@Column(name = "SELLER_LOCATION_LONGITUDE")
	private double sellerLocationLongitude;
	@Column(name = "SELLER_KYC_DOC_TYPE")
	private String sellerKycDocType;
	@Column(name = "SELLER_KYC_DOC_VALUE")
	private String sellerKycDocValue;
	@Column(name = "SELLER_CREATED_TIME", insertable = false, updatable = false)
	private Date sellerCreatedTime;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SELLER_UPDATED_TIME")
	@Version
	private Date sellerUpdatedTime;
	@Column(name = "SELLER_TYPE")
	private String sellerType;
	@Column(name = "SELLER_SHOP_NAME")
	private String sellerShopName;
	@Column(name = "SELLER_ROLE")
	private String sellerRole;
	@Column(name = "AMBASSADOR_MOBILE")
	private String ambassadorMobile;
	@Column(name = "SELLER_SETTLE_PREF")
	private int sellerSettlePref;
	/*
	 * @Column(name="KYC_DOC_IMG") private String kycDocImage;
	 */
	@Column(name = "ISACTIVE")
	private int isActive;
	@Column(name = "MOBILE_ALIAS")
	private String mobileAlias;
	@Column(name = "BRANDING_URL")
	private String branding_url;
	@Column(name = "BUSINESS_TYPE")
	private String businessType;
	@Column(name = "IS_DELETED")
	private Integer isDeleted;
	@Column(name = "EXTRA_EMAILS")
	private String extraEmails;
	@Column(name = "TAG")
	private String tag;
	@Column(name = "BUSINESS_CATEGORY")
	private String businessCategory;
	@Column(name = "MAP_MARKER_NAME")
	private String mapMarkerName;
	@Column(name = "ABOUT_SELLER")
	private String aboutSeller;
	@Column(name = "COBRANDING", nullable = false, columnDefinition = "TINYINT(1)")
	private boolean cobranding = true;
	@Column(name = "SELLER_ICON_URL")
	private String sellerIconURL;
	@Column(name = "ECOM_PAYMENT")
	private Integer ecomPayment;
	@Formula("(SELECT avg(R.rating)  FROM llcdb.entity_rating R where R.entity_id= seller_id and  R.entity_type='S')")
	private Float rating = 0f;

	
	public EngageSeller() {
	}

	public EngageSeller(int citrusSellerId, String sellerName, String sellerEmail99, String sellerPasswd99,
			String sellerCountryCode, String sellerMobileNumber, String sellerCountry, String sellerCity,
			String sellerAddress, float sellerSplitPercent, Date sellerCreatedTime, Date sellerUpdatedTime) {
		// this.citrusSellerId = citrusSellerId;
		this.sellerName = sellerName;
		this.sellerEmail99 = sellerEmail99;
		this.sellerPasswd99 = sellerPasswd99;
		this.sellerCountryCode = sellerCountryCode;
		this.sellerMobileNumber = sellerMobileNumber;
		this.sellerCountry = sellerCountry;
		this.sellerCity = sellerCity;
		this.sellerAddress = sellerAddress;
		this.sellerCreatedTime = sellerCreatedTime;
		this.sellerUpdatedTime = sellerUpdatedTime;
	}

	public EngageSeller(int citrusSellerId, String sellerName, String sellerEmail99, String sellerPasswd99,
			String sellerCountryCode, String sellerMobileNumber, String sellerCountry, String sellerCity,
			String sellerAddress, String sellerDeviceId, double sellerLocationLatitude, double sellerLocationLongitude,
			float sellerSplitPercent, String sellerKycDocType, String sellerKycDocValue, Date sellerCreatedTime,
			Date sellerUpdatedTime) {
		// this.citrusSellerId = citrusSellerId;
		this.sellerName = sellerName;
		this.sellerEmail99 = sellerEmail99;
		this.sellerPasswd99 = sellerPasswd99;
		this.sellerCountryCode = sellerCountryCode;
		this.sellerMobileNumber = sellerMobileNumber;
		this.sellerCountry = sellerCountry;
		this.sellerCity = sellerCity;
		this.sellerAddress = sellerAddress;
		this.sellerDeviceId = sellerDeviceId;
		this.sellerLocationLatitude = sellerLocationLatitude;
		this.sellerLocationLongitude = sellerLocationLongitude;
		this.sellerKycDocType = sellerKycDocType;
		this.sellerKycDocValue = sellerKycDocValue;
		this.sellerCreatedTime = sellerCreatedTime;
		this.sellerUpdatedTime = sellerUpdatedTime;
	}

	public int getSellerId() {
		return this.sellerId;
	}

	public void setSellerId(int sellerId) {
		this.sellerId = sellerId;
	}

	public String getSellerName() {
		return this.sellerName;
	}

	public void setSellerName(String sellerName) {
		this.sellerName = sellerName;
	}

	public String getSellerEmail99() {
		return this.sellerEmail99;
	}

	public void setSellerEmail99(String sellerEmail99) {
		this.sellerEmail99 = sellerEmail99;
	}

	public String getSellerPasswd99() {
		return this.sellerPasswd99;
	}

	public void setSellerPasswd99(String sellerPasswd99) {
		this.sellerPasswd99 = sellerPasswd99;
	}

	public String getSellerCountryCode() {
		return this.sellerCountryCode;
	}

	public void setSellerCountryCode(String sellerCountryCode) {
		this.sellerCountryCode = sellerCountryCode;
	}

	public String getSellerMobileNumber() {
		return this.sellerMobileNumber;
	}

	public void setSellerMobileNumber(String sellerMobileNumber) {
		this.sellerMobileNumber = sellerMobileNumber;
	}

	public String getSellerCountry() {
		return this.sellerCountry;
	}

	public void setSellerCountry(String sellerCountry) {
		this.sellerCountry = sellerCountry;
	}

	public String getSellerCity() {
		return this.sellerCity;
	}

	public void setSellerCity(String sellerCity) {
		this.sellerCity = sellerCity;
	}

	public String getSellerAddress() {
		return this.sellerAddress;
	}

	public void setSellerAddress(String sellerAddress) {
		this.sellerAddress = sellerAddress;
	}

	public double getSellerLocationLatitude() {
		return this.sellerLocationLatitude;
	}

	public void setSellerLocationLatitude(double sellerLocationLatitude) {
		this.sellerLocationLatitude = sellerLocationLatitude;
	}

	public double getSellerLocationLongitude() {
		return this.sellerLocationLongitude;
	}

	public void setSellerLocationLongitude(double sellerLocationLongitude) {
		this.sellerLocationLongitude = sellerLocationLongitude;
	}

	public String getSellerKycDocType() {
		return this.sellerKycDocType;
	}

	public void setSellerKycDocType(String sellerKycDocType) {
		this.sellerKycDocType = sellerKycDocType;
	}

	public String getSellerKycDocValue() {
		return this.sellerKycDocValue;
	}

	public void setSellerKycDocValue(String sellerKycDocValue) {
		this.sellerKycDocValue = sellerKycDocValue;
	}

	public Date getSellerCreatedTime() {
		return this.sellerCreatedTime;
	}

	public void setSellerCreatedTime(Date sellerCreatedTime) {
		this.sellerCreatedTime = sellerCreatedTime;
	}

	public Date getSellerUpdatedTime() {
		return this.sellerUpdatedTime;
	}

	public void setSellerUpdatedTime(Date sellerUpdatedTime) {
		this.sellerUpdatedTime = sellerUpdatedTime;
	}

	public String getSellerDeviceId() {
		return sellerDeviceId;
	}

	public void setSellerDeviceId(String sellerDeviceId) {
		this.sellerDeviceId = sellerDeviceId;
	}

	public String getSellerType() {
		return sellerType;
	}

	public void setSellerType(String sellerType) {
		this.sellerType = sellerType;
	}

	public String getSellerShopName() {
		return sellerShopName;
	}

	public void setSellerShopName(String sellerShopName) {
		this.sellerShopName = sellerShopName;
	}

	public String getSellerRole() {
		return sellerRole;
	}

	public void setSellerRole(String sellerRole) {
		this.sellerRole = sellerRole;
	}

	public int getSellerSettlePref() {
		return sellerSettlePref;
	}

	public void setSellerSettlePref(int sellerSettlePref) {
		this.sellerSettlePref = sellerSettlePref;
	}

	/*
	 * public String getKycDocImage() { return kycDocImage; }
	 * 
	 * public void setKycDocImage(String kycDocImage) { this.kycDocImage =
	 * kycDocImage; }
	 */

	public int getIsActive() {
		return isActive;
	}

	public void setIsActive(int isActive) {
		this.isActive = isActive;
	}

	public String getAmbassadorMobile() {
		return ambassadorMobile;
	}

	public void setAmbassadorMobile(String ambassadorMobile) {
		this.ambassadorMobile = ambassadorMobile;
	}

	public String getMobileAlias() {
		return mobileAlias;
	}

	public void setMobileAlias(String mobileAlias) {
		this.mobileAlias = mobileAlias;
	}

	public String getBranding_url() {
		return branding_url;
	}

	public void setBranding_url(String branding_url) {
		this.branding_url = branding_url;
	}

	public String getBusinessType() {
		return businessType;
	}

	public void setBusinessType(String businessType) {
		this.businessType = businessType;
	}

	public Integer getIsDeleted() {
		return isDeleted;
	}

	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

	public String getExtraEmails() {
		return extraEmails;
	}

	public void setExtraEmails(String extraEmails) {
		this.extraEmails = extraEmails;
	}

	public String getTag() {
		return tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	public String getBusinessCategory() {
		return businessCategory == null || businessCategory.equalsIgnoreCase("") ? "Shop" : businessCategory;
	}

	public void setBusinessCategory(String businessCategory) {
		this.businessCategory = businessCategory;
	}

	public String getMapMarkerName() {
		return mapMarkerName == null || mapMarkerName.equalsIgnoreCase("") ? "default" : mapMarkerName;
	}

	public void setMapMarkerName(String mapMarkerName) {
		this.mapMarkerName = mapMarkerName;
	}

	public String getAboutSeller() {
		return aboutSeller;
	}

	public void setAboutSeller(String aboutSeller) {
		this.aboutSeller = aboutSeller;
	}

	public boolean isCobranding() {
		return cobranding;
	}

	public void setCobranding(boolean cobranding) {
		this.cobranding = cobranding;
	}

	public String getSellerIconURL() {
		return sellerIconURL;
	}

	public void setSellerIconURL(String sellerIconURL) {
		this.sellerIconURL = sellerIconURL;
	}

	public Integer getEcomPayment() {
		return ecomPayment;
	}

	public void setEcomPayment(Integer ecomPayment) {
		this.ecomPayment = ecomPayment;
	}

	public Float getRating() {
		return rating == null ? 0 : rating;
	}

}
