package com.limitless.services.payment.PaymentService.dao;

/*
 * @author veejay.developer@gmail.com
 * ©www.limitlesscircle.com 
 */

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * PaymentTxn generated by hbm2java
 */

@Entity
@Table(name = "payment_txn", catalog = "llcdb")
public class PaymentTxn implements java.io.Serializable {
	
	@Id @GeneratedValue
	@Column(name="TXN_ID")
	private int txnId;
	@Column(name="ENGAGE_CUSTOMER_ID")
	private int engageCustomerId;
	@Column(name="SELLER_ID")
	private int sellerId;
	@Column(name="CITRUS_SELLER_ID")
	private int citrusSellerId;
	@Column(name="SELLER_NAME")
	private String sellerName;
	@Column(name="SELLER_DEVICE_ID")
	private String sellerDeviceId;
	@Column(name="TXN_AMOUNT")
	private float txnAmount;
	@Column(name="CITRUS_MP_TXN_ID")
	private int citrusMpTxnId;
	@Column(name="SPLIT_ID")
	private int splitId;
	@Column(name="TXN_STATUS")
	private String txnStatus;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="TXN_CREATED_TIME", insertable = false, updatable = false)
	private Date txnCreatedTime;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="TXN_UPDATED_TIME")
	@Version
	private Date txnUpdatedTime;
	@Column(name="TXN_NOTES")
	private String txnNotes;
	@Column(name="ORDER_ID")
	private Integer orderId;
	@Column(name="TXN_TYPE")
	private String txnType;

	public PaymentTxn() {
	}

	public PaymentTxn(int engageCustomerId, int sellerId, int citrusSellerId, String sellerName, float txnAmount,
			Date txnCreatedTime, Date txnUpdatedTime) {
		this.engageCustomerId = engageCustomerId;
		this.sellerId = sellerId;
		this.citrusSellerId = citrusSellerId;
		this.sellerName = sellerName;
		this.txnAmount = txnAmount;
		this.txnCreatedTime = txnCreatedTime;
		this.txnUpdatedTime = txnUpdatedTime;
	}

	public PaymentTxn(int engageCustomerId, int sellerId, int citrusSellerId, String sellerName, float txnAmount,
			int citrusMpTxnId, int splitId, String txnStatus,
			Date txnCreatedTime, Date txnUpdatedTime) {
		this.engageCustomerId = engageCustomerId;
		this.sellerId = sellerId;
		this.citrusSellerId = citrusSellerId;
		this.sellerName = sellerName;
		this.txnAmount = txnAmount;
		this.citrusMpTxnId = citrusMpTxnId;
		this.splitId = splitId;
		this.txnStatus = txnStatus;
		this.txnCreatedTime = txnCreatedTime;
		this.txnUpdatedTime = txnUpdatedTime;
	}

	public int getTxnId() {
		return this.txnId;
	}

	public void setTxnId(int txnId) {
		this.txnId = txnId;
	}

	public int getSellerId() {
		return this.sellerId;
	}

	public void setSellerId(int sellerId) {
		this.sellerId = sellerId;
	}

	public String getSellerName() {
		return this.sellerName;
	}

	public void setSellerName(String sellerName) {
		this.sellerName = sellerName;
	}

	public float getTxnAmount() {
		return this.txnAmount;
	}

	public void setTxnAmount(float txnAmount) {
		this.txnAmount = txnAmount;
	}
	
	public int getSplitId() {
		return this.splitId;
	}

	public void setSplitId(int splitId) {
		this.splitId = splitId;
	}

	public Date getTxnCreatedTime() {
		return this.txnCreatedTime;
	}

	public void setTxnCreatedTime(Date txnCreatedTime) {
		this.txnCreatedTime = txnCreatedTime;
	}

	public Date getTxnUpdatedTime() {
		return this.txnUpdatedTime;
	}

	public void setTxnUpdatedTime(Date txnUpdatedTime) {
		this.txnUpdatedTime = txnUpdatedTime;
	}

	public int getCitrusMpTxnId() {
		return citrusMpTxnId;
	}

	public void setCitrusMpTxnId(int citrusMpTxnId) {
		this.citrusMpTxnId = citrusMpTxnId;
	}

	public String getTxnStatus() {
		return txnStatus;
	}

	public void setTxnStatus(String txnStatus) {
		this.txnStatus = txnStatus;
	}
	
	public int getEngageCustomerId() {
		return engageCustomerId;
	}

	public void setEngageCustomerId(int engageCustomerId) {
		this.engageCustomerId = engageCustomerId;
	}

	public String getSellerDeviceId() {
		return sellerDeviceId;
	}

	public void setSellerDeviceId(String sellerDeviceId) {
		this.sellerDeviceId = sellerDeviceId;
	}

	public int getCitrusSellerId() {
		return citrusSellerId;
	}

	public void setCitrusSellerId(int citrusSellerId) {
		this.citrusSellerId = citrusSellerId;
	}

	public String getTxnNotes() {
		return txnNotes;
	}

	public void setTxnNotes(String txnNotes) {
		this.txnNotes = txnNotes;
	}

	public Integer getOrderId() {
		return orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public String getTxnType() {
		return txnType;
	}

	public void setTxnType(String txnType) {
		this.txnType = txnType;
	}

	@Override
	public String toString() {
		return "PaymentTxn [txnId=" + txnId + ", engageCustomerId=" + engageCustomerId + ", sellerId=" + sellerId
				+ ", citrusSellerId=" + citrusSellerId + ", sellerName=" + sellerName + ", sellerDeviceId="
				+ sellerDeviceId + ", txnAmount=" + txnAmount + ", citrusMpTxnId=" + citrusMpTxnId + ", splitId="
				+ splitId + ", txnStatus=" + txnStatus + ", txnCreatedTime=" + txnCreatedTime + ", txnUpdatedTime="
				+ txnUpdatedTime + ", txnNotes=" + txnNotes + "]";
	}
}
