package com.limitless.services.payment.PaymentService.dao;

// Generated Oct 19, 2016 7:49:46 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * PaymentCredit generated by hbm2java
 */
@Entity
@Table(name = "payment_credit", catalog = "llcdb")
public class PaymentCredit implements java.io.Serializable {
	
	@Id @GeneratedValue
	@Column(name="CREDIT_ID")
	private Integer creditId;
	@Column(name="TXN_ID")
	private Integer txnId;
	@Column(name="CREDIT_AMOUNT")
	private float creditAmount;
	@Column(name="DEBIT_AMOUNT")
	private float debitAmount;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="CREDIT_CREATED_TIME")
	private Date creditCreatedTime;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="CREDIT_UPDATED_TIME")
	@Version
	private Date creditUpdatedTime;

	public PaymentCredit() {
	}

	public PaymentCredit(int txnId, float creditAmount,
			float debitAmount, Date creditCreatedTime, Date creditUpdatedTime) {
		this.txnId = txnId;
		this.creditAmount = creditAmount;
		this.debitAmount = debitAmount;
		this.creditCreatedTime = creditCreatedTime;
		this.creditUpdatedTime = creditUpdatedTime;
	}

	public Integer getTxnId() {
		return txnId;
	}

	public void setTxnId(Integer txnId) {
		this.txnId = txnId;
	}

	public Integer getCreditId() {
		return this.creditId;
	}

	public void setCreditId(Integer creditId) {
		this.creditId = creditId;
	}

	public float getCreditAmount() {
		return this.creditAmount;
	}

	public void setCreditAmount(float creditAmount) {
		this.creditAmount = creditAmount;
	}

	public float getDebitAmount() {
		return this.debitAmount;
	}

	public void setDebitAmount(float debitAmount) {
		this.debitAmount = debitAmount;
	}

	public Date getCreditCreatedTime() {
		return this.creditCreatedTime;
	}

	public void setCreditCreatedTime(Date creditCreatedTime) {
		this.creditCreatedTime = creditCreatedTime;
	}

	public Date getCreditUpdatedTime() {
		return this.creditUpdatedTime;
	}

	public void setCreditUpdatedTime(Date creditUpdatedTime) {
		this.creditUpdatedTime = creditUpdatedTime;
	}

}
