package com.limitless.services.payment.PaymentService.dao;

/*
 * @author veejay.developer@gmail.com
 * ©www.limitlesscircle.com 
 */

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * PaymentTxn generated by hbm2java
 */

@Entity
@Table(name = "payment_txn", catalog = "llcdb")
public class PaymentTxn implements java.io.Serializable {
	
	@Id @GeneratedValue
	@Column(name="TXN_ID")
	private int txnId;
	@Column(name="SELLER_ID")
	private String sellerId;
	@Column(name="SELLER_NAME")
	private String sellerName;
	@Column(name="TXN_AMOUNT")
	private float txnAmount;
	@Column(name="CITRUS_MP_TXN_ID")
	private String citrusMpTxnId;
	@Column(name="SPLIT_ID")
	private String splitId;
	@Column(name="TXN_STATUS")
	private String txnStatus;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="TXN_CREATED_TIME")
	private Date txnCreatedTime;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="TXN_UPDATED_TIME")
	@Version
	private Date txnUpdatedTime;

	public PaymentTxn() {
	}

	public PaymentTxn(String sellerId, String sellerName, float txnAmount,
			Date txnCreatedTime, Date txnUpdatedTime) {
		this.sellerId = sellerId;
		this.sellerName = sellerName;
		this.txnAmount = txnAmount;
		this.txnCreatedTime = txnCreatedTime;
		this.txnUpdatedTime = txnUpdatedTime;
	}

	public PaymentTxn(String sellerId, String sellerName, float txnAmount,
			String citrusMpTxnId, String splitId, String txnStatus,
			Date txnCreatedTime, Date txnUpdatedTime) {
		this.sellerId = sellerId;
		this.sellerName = sellerName;
		this.txnAmount = txnAmount;
		this.citrusMpTxnId = citrusMpTxnId;
		this.splitId = splitId;
		this.txnStatus = txnStatus;
		this.txnCreatedTime = txnCreatedTime;
		this.txnUpdatedTime = txnUpdatedTime;
	}

	public int getTxnId() {
		return this.txnId;
	}

	public void setTxnId(int txnId) {
		this.txnId = txnId;
	}

	public String getSellerId() {
		return this.sellerId;
	}

	public void setSellerId(String sellerId) {
		this.sellerId = sellerId;
	}

	public String getSellerName() {
		return this.sellerName;
	}

	public void setSellerName(String sellerName) {
		this.sellerName = sellerName;
	}

	public float getTxnAmount() {
		return this.txnAmount;
	}

	public void setTxnAmount(float txnAmount) {
		this.txnAmount = txnAmount;
	}
	
	public String getSplitId() {
		return this.splitId;
	}

	public void setSplitId(String splitId) {
		this.splitId = splitId;
	}

	public Date getTxnCreatedTime() {
		return this.txnCreatedTime;
	}

	public void setTxnCreatedTime(Date txnCreatedTime) {
		this.txnCreatedTime = txnCreatedTime;
	}

	public Date getTxnUpdatedTime() {
		return this.txnUpdatedTime;
	}

	public void setTxnUpdatedTime(Date txnUpdatedTime) {
		this.txnUpdatedTime = txnUpdatedTime;
	}

	public String getCitrusMpTxnId() {
		return citrusMpTxnId;
	}

	public void setCitrusMpTxnId(String citrusMpTxnId) {
		this.citrusMpTxnId = citrusMpTxnId;
	}

	public String getTxnStatus() {
		return txnStatus;
	}

	public void setTxnStatus(String txnStatus) {
		this.txnStatus = txnStatus;
	}
	
}
