package com.limitless.services.payment.PaymentService.dao;

// Generated Aug 6, 2016 10:06:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * PaymentTxn generated by hbm2java
 */

@Entity
@Table(name = "payment_txn", catalog = "llcdb")
public class PaymentTxn implements java.io.Serializable {
	
	@Id
	@Column(name="TXN_ID")
	private int txnId;
	@Column(name="SELLER_ID")
	private int sellerId;
	@Column(name="SELLER_NAME")
	private String sellerName;
	@Column(name="TXN_AMOUNT")
	private float txnAmount;
	@Column(name="SPLIT_ID")
	private Integer splitId;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="TXN_CREATED_TIME")
	private Date txnCreatedTime;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="TXN_UPDATED_TIME")
	@Version
	private Date txnUpdatedTime;

	public PaymentTxn() {
	}

	public PaymentTxn(int txnId, int sellerId, String sellerName,
			float txnAmount, Date txnCreatedTime, Date txnUpdatedTime) {
		this.txnId = txnId;
		this.sellerId = sellerId;
		this.sellerName = sellerName;
		this.txnAmount = txnAmount;
		this.txnCreatedTime = txnCreatedTime;
		this.txnUpdatedTime = txnUpdatedTime;
	}
	
	public PaymentTxn(int txnId, int sellerId, String sellerName,
			float txnAmount, Integer splitId, Date txnCreatedTime,
			Date txnUpdatedTime) {
		this.txnId = txnId;
		this.sellerId = sellerId;
		this.sellerName = sellerName;
		this.txnAmount = txnAmount;
		this.splitId = splitId;
		this.txnCreatedTime = txnCreatedTime;
		this.txnUpdatedTime = txnUpdatedTime;
	}

	public int getTxnId() {
		return this.txnId;
	}

	public void setTxnId(int txnId) {
		this.txnId = txnId;
	}

	public int getSellerId() {
		return this.sellerId;
	}

	public void setSellerId(int sellerId) {
		this.sellerId = sellerId;
	}

	public String getSellerName() {
		return this.sellerName;
	}

	public void setSellerName(String sellerName) {
		this.sellerName = sellerName;
	}

	public float getTxnAmount() {
		return this.txnAmount;
	}

	public void setTxnAmount(float txnAmount) {
		this.txnAmount = txnAmount;
	}
	
	public Integer getSplitId() {
		return this.splitId;
	}

	public void setSplitId(Integer splitId) {
		this.splitId = splitId;
	}

	public Date getTxnCreatedTime() {
		return this.txnCreatedTime;
	}

	public void setTxnCreatedTime(Date txnCreatedTime) {
		this.txnCreatedTime = txnCreatedTime;
	}

	public Date getTxnUpdatedTime() {
		return this.txnUpdatedTime;
	}

	public void setTxnUpdatedTime(Date txnUpdatedTime) {
		this.txnUpdatedTime = txnUpdatedTime;
	}

}
