package com.limitless.services.payment.PaymentService.util;

public class PaymentConstants {
	public static final String AUTH_TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY2Nlc3Nfa2V5IjoiOTZLMzRRNEE4SThOUkVIN05WT1oiLCJleHBpcmVzIjoiMjAxNi0xMS0zMFQwNzo1Nzo1Mi45NzNaIiwiY2FuX3RyYW5zYWN0IjoxLCJhZG1pbiI6MH0.vHryhK4Z_7sVgKqFxNsJ_oPQriPVR74KDk393ZPn-G4";
}
