package com.limitless.services.payment.PaymentService.util;

public class PaymentConstants {
	public static final String AUTH_TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY2Nlc3Nfa2V5IjoiOTZLMzRRNEE4SThOUkVIN05WT1oiLCJleHBpcmVzIjoiMjAxNi0xMS0xOVQwNjoyMzo0NC4zMjdaIiwiY2FuX3RyYW5zYWN0IjoxLCJhZG1pbiI6MH0.ptqshhaCcrh0W1MYrr7MblITp0cvo_v9-A65VLkjlBU";
}
